create table propietario(
    nit varchar(10) primary key,
    nombre varchar(100) not null,
    cui_p varchar(15) not null unique
);

create table usuario(
    id_usuario integer generated by default as identity primary key,
    password varchar(255) not null,
    nit_usuario_fk varchar(10) not null unique,

    constraint propietario_usuario_fk
        foreign key (nit_usuario_fk)
        references propietario (nit)
        on update cascade
        on delete restrict
);

create table uso_vehiculo(
    id_uso integer generated by default as identity primary key,
    uso varchar(50) not null unique
);

create table color(
    id_color integer generated by default as identity primary key,
    color varchar(50) not null unique,
    detalles varchar(100)
);

create table marca_vehiculo(
    id_marca integer generated by default as identity primary key,
    marca varchar(50) not null unique
);

create table tipo_vehiculo(
    id_tipo integer generated by default as identity primary key,
    tipo varchar(50) not null unique
);

create table linea_vehiculo(
    id_linea integer generated by default as identity primary key,
    linea varchar(50) not null,
    id_marca_fk integer not null,

    constraint marca_fk
        foreign key (id_marca_fk)
        references marca_vehiculo (id_marca)
        on update cascade
        on delete restrict
);

create table vehiculo(
    id_vehiculo integer generated by default as identity primary key,
    vin varchar(20) not null unique,
    chasis varchar(20) not null unique,
    serie varchar(20) not null,
    modelo integer not null,
    cilindros integer not null,
    asientos integer not null,
    ejes integer not null,
    cc integer not null,
    ton integer not null,
    id_linea_fk integer not null,
    id_tipo_fk integer not null,

    constraint linea_fk
        foreign key (id_linea_fk)
        references linea_vehiculo (id_linea)
        on update cascade
        on delete restrict,

    constraint tipo_fk
        foreign key (id_tipo_fk)
        references tipo_vehiculo (id_tipo)
        on update cascade
        on delete restrict
);

create table estado_vehiculo(
    id_estado integer generated by default as identity primary key,
    placa varchar(10) not null,
    motor varchar(20) not null,
    fecha_actualizacion date not null,
    motivo_cambio varchar(255) not null,
    id_uso_fk integer not null,
    id_color_fk integer not null,
    id_vehiculo_fk integer not null,

    constraint uso_fk
        foreign key (id_uso_fk)
        references uso_vehiculo (id_uso)
        on update cascade
        on delete restrict,

    constraint color_fk
        foreign key (id_color_fk)
        references color (id_color)
        on update cascade
        on delete restrict,

    constraint vehiculo_fk
        foreign key (id_vehiculo_fk)
        references vehiculo (id_vehiculo)
        on update cascade
        on delete restrict
);

create table tarjeta_circulacion(
    numero integer primary key,
    cui_tc varchar(20) not null unique,
    fecha_registro date not null,
    fecha_vencimiento date not null,
    fecha_emision date not null,
    hora_emision time not null,
    estado boolean not null,
    nit_propietario_fk varchar(10) not null,
    id_estado_vehiculo_fk integer not null,

    constraint propietario_tc_fk
        foreign key (nit_propietario_fk)
        references propietario (nit)
        on update cascade
        on delete restrict,

    constraint estado_vehiculo_fk
        foreign key (id_estado_vehiculo_fk)
        references estado_vehiculo (id_estado)
        on update cascade
        on delete restrict
);